name: beforedoctor
description: "Voice-driven health app for symptom logging, clinic prep (save 5-15 min/visit)."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # UI & Animation
  get: ^4.6.6
  getwidget: ^6.0.0  # Fixed package name
  rive: ^0.13.0  # Fixed version for compatibility
  lottie: ^3.1.0

  # State Management
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1

  # Database & Storage
  sqflite: ^2.3.3+1
  firebase_core: ^3.15.2
  firebase_database: ^11.3.10
  firebase_auth: ^5.7.0

  # Voice & AI
  google_ml_kit: ^0.18.1
  dart_openai: ^5.1.0
  flutter_tts: ^3.8.5
  just_audio: ^0.9.46
  audio_session: ^0.1.25

  # Utilities
  logger: ^2.0.2+1
  permission_handler: ^11.4.0
  geolocator: ^12.0.0
  http: ^1.4.0  # Reverted to original version
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  flutter_dotenv: ^5.1.0  # Added back for environment config
  path: ^1.9.0  # Added back for file handling
  
  # Localization
  flutter_localizations:
    sdk: flutter

  # 3D Rendering - CUSTOM SOLUTION (NO WebView!)
  # three_dart: ^0.0.8  # COMMENTED OUT - HTTP version conflict
  # flutter_gl: ^0.0.2  # COMMENTED OUT - Android namespace issues
  # model_viewer_plus: ^1.7.0  # COMMENTED OUT - causes WebView memory leaks
  # webview_flutter: ^4.7.0  # COMMENTED OUT - no longer needed
  # flutter_3d_controller: ^1.3.1  # COMMENTED OUT - has WebView dependency causing memory leaks

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  mockito: ^5.4.4  # Unit testing
  build_runner: ^2.4.8
  sqflite_common_ffi: ^2.3.3  # For testing SQLite

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/characters/
    - assets/3d/
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/models/
    - .env
  
  # Localization support
  generate: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
